-- =============================================================================
-- 02_users.sql
-- Users table for dashboard auth (PRD §F13).
--
-- One seeded dev user (`dev` / `devpass`) so the dashboard works after a
-- fresh `make up`. In production, replace this seed with a real user via
-- the admin UI (deferred to TODOS.md::user-mgmt-ui).
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
    id            SERIAL      PRIMARY KEY,
    username      TEXT        UNIQUE NOT NULL,
    password_hash TEXT        NOT NULL,                    -- bcrypt
    role          TEXT        NOT NULL DEFAULT 'analyst'
                              CHECK (role IN ('analyst', 'admin', 'ops')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- bcrypt('devpass') — generated by passlib at plan time.
-- Anyone with read access to this file can log in as dev — that's the point;
-- it's a development convenience.  Do NOT use this hash in any environment
-- that is reachable from the internet.
INSERT INTO users (username, password_hash, role)
VALUES (
    'dev',
    '$2b$12$MIbAUDqh1Tj235R7RepLn.h/MUWIbi9SM5J2jXcTJeIKdo7jleR02',
    'analyst'
)
ON CONFLICT (username) DO NOTHING;
